from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent

CAMERA_SRC = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720

YOLO_MODEL_NAME = "yolo11s"
YOLO_PT_PATH = BASE_DIR / f"{YOLO_MODEL_NAME}.pt"
YOLO_ONNX_PATH = BASE_DIR / f"{YOLO_MODEL_NAME}.onnx"
YOLO_CONFIDENCE = 0.5
YOLO_IMAGE_SIZE = 640

HAND_LANDMARKER_PATH = BASE_DIR / "hand_landmarker.task"
HAND_NUM_HANDS = 1
HAND_MIN_DETECTION_CONFIDENCE = 0.6
HAND_MIN_PRESENCE_CONFIDENCE = 0.6
HAND_MIN_TRACKING_CONFIDENCE = 0.6

FRAME_QUEUE_SIZE = 1
